<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="3" total="9" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Suite1" duration-ms="498" started-at="2020-08-30T10:25:49Z" finished-at="2020-08-30T10:25:50Z">
    <groups>
      <group name="checkintest">
        <method signature="TestNG_Flow.firstTest()[pri:2, instance:com.TestNG.TestNG_Flow@2ac273d3]" name="firstTest" class="com.TestNG.TestNG_Flow"/>
        <method signature="TestNG_Flow.thirdTest()[pri:3, instance:com.TestNG.TestNG_Flow@2ac273d3]" name="thirdTest" class="com.TestNG.TestNG_Flow"/>
      </group> <!-- checkintest -->
      <group name="functest">
        <method signature="TestNG_Flow.firstTest()[pri:2, instance:com.TestNG.TestNG_Flow@2ac273d3]" name="firstTest" class="com.TestNG.TestNG_Flow"/>
        <method signature="TestNG_Flow.secondTest()[pri:1, instance:com.TestNG.TestNG_Flow@2ac273d3]" name="secondTest" class="com.TestNG.TestNG_Flow"/>
      </group> <!-- functest -->
      <group name="group1">
        <method signature="TestngAnnotation.testCase2(java.lang.String)[pri:0, instance:com.TestNG.TestngAnnotation@cb644e]" name="testCase2" class="com.TestNG.TestngAnnotation"/>
        <method signature="TestngAnnotation.testCase5()[pri:0, instance:com.TestNG.TestngAnnotation@cb644e]" name="testCase5" class="com.TestNG.TestngAnnotation"/>
      </group> <!-- group1 -->
      <group name="group">
        <method signature="TestngAnnotation.testCase4()[pri:0, instance:com.TestNG.TestngAnnotation@cb644e]" name="testCase4" class="com.TestNG.TestngAnnotation"/>
      </group> <!-- group -->
    </groups>
    <test name="TestngAnnotation-test1" duration-ms="256" started-at="2020-08-30T10:25:49Z" finished-at="2020-08-30T10:25:49Z">
      <class name="com.TestNG.TestngAnnotation">
        <test-method status="PASS" signature="testCase2(java.lang.String)[pri:0, instance:com.TestNG.TestngAnnotation@cb644e]" name="testCase2" duration-ms="50" started-at="2020-08-30T10:25:49Z" finished-at="2020-08-30T10:25:49Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[manisha]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase2 -->
        <test-method status="FAIL" signature="testCase5()[pri:0, instance:com.TestNG.TestngAnnotation@cb644e]" name="testCase5" duration-ms="6" started-at="2020-08-30T10:25:49Z" finished-at="2020-08-30T10:25:49Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.TestNG.TestngAnnotation.testCase5(TestngAnnotation.java:63)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase5 -->
        <test-method status="SKIP" signature="testCase4()[pri:0, instance:com.TestNG.TestngAnnotation@cb644e]" name="testCase4" duration-ms="0" depends-on-groups="group1" started-at="2020-08-30T10:25:49Z" finished-at="2020-08-30T10:25:49Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestngAnnotation.testCase4()[pri:0, instance:com.TestNG.TestngAnnotation@cb644e] depends on not successfully finished methods in group "group1"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestngAnnotation.testCase4()[pri:0, instance:com.TestNG.TestngAnnotation@cb644e] depends on not successfully finished methods in group "group1"
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase4 -->
      </class> <!-- com.TestNG.TestngAnnotation -->
    </test> <!-- TestngAnnotation-test1 -->
    <test name="TestNG-test2" duration-ms="46" started-at="2020-08-30T10:25:50Z" finished-at="2020-08-30T10:25:50Z">
      <class name="com.TestNG.TestNG_Flow">
        <test-method status="PASS" signature="secondTest()[pri:1, instance:com.TestNG.TestNG_Flow@2ac273d3]" name="secondTest" duration-ms="5" started-at="2020-08-30T10:25:50Z" finished-at="2020-08-30T10:25:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- secondTest -->
        <test-method status="PASS" signature="firstTest()[pri:2, instance:com.TestNG.TestNG_Flow@2ac273d3]" name="firstTest" duration-ms="6" started-at="2020-08-30T10:25:50Z" finished-at="2020-08-30T10:25:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- firstTest -->
        <test-method status="PASS" signature="thirdTest()[pri:3, instance:com.TestNG.TestNG_Flow@2ac273d3]" name="thirdTest" duration-ms="9" started-at="2020-08-30T10:25:50Z" finished-at="2020-08-30T10:25:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- thirdTest -->
      </class> <!-- com.TestNG.TestNG_Flow -->
    </test> <!-- TestNG-test2 -->
  </suite> <!-- Suite1 -->
</testng-results>
